%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

Name:           ros-kilted-mola-state-estimation-smoother
Version:        1.11.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS mola_state_estimation_smoother package

License:        GPLv3
URL:            https://github.com/MOLAorg/mola_state_estimation
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kilted-gtsam
Requires:       ros-kilted-mola-common
Requires:       ros-kilted-mola-imu-preintegration
Requires:       ros-kilted-mola-kernel
Requires:       ros-kilted-mrpt-libobs
Requires:       ros-kilted-ros-workspace
BuildRequires:  boost-devel
BuildRequires:  cmake3
BuildRequires:  ros-kilted-gtsam
BuildRequires:  ros-kilted-mola-common
BuildRequires:  ros-kilted-mola-imu-preintegration
BuildRequires:  ros-kilted-mola-kernel
BuildRequires:  ros-kilted-mrpt-libobs
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
SE(3) pose and twist path data fusion estimator

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
%license LICENSE
/opt/ros/kilted

%changelog
* Sun Oct 05 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.11.0-1
- Autogenerated by Bloom

* Sun Sep 07 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.10.0-1
- Autogenerated by Bloom

* Fri Jun 06 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.9.0-1
- Autogenerated by Bloom

* Sun May 25 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.8.1-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.8.0-2
- Autogenerated by Bloom

* Sat Mar 15 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.8.0-1
- Autogenerated by Bloom

* Sat Feb 22 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.7.0-1
- Autogenerated by Bloom

* Fri Jan 10 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.1-1
- Autogenerated by Bloom

* Fri Jan 03 2025 Jose-Luis Blanco-Claraco <joseluisblancoc@gmail.com> - 1.6.0-1
- Autogenerated by Bloom

